### ISSUE TITLE
Delete admin user

### ISSUE THREAD

**Issue by Pofilo** [GladysAssistant/gladys-gateway#22]
Hello,

Actually, deleting my own admin account is not possible on [https://gateway.gladysassistant.com/dashboard/users](https://gateway.gladysassistant.com/dashboard/users). Due to GRPD, every user should be able to delete their account at any time.

This feature is actually missing from the gateway.

Pofilo.

**Comment by Pierre-Gilles** [comment]
Hey!

Good point, it's true that it's would be nice feature to have :)

But it's really not as simple as the "delete invitation" button on the admin tab which just invalidate an invitation in DB. 

In the case of a "delete account" request, we have to hard delete the data everywhere:

- Hard delete in database
- Hard delete on Stripe
- List all encrypted backups, loop on each and hard delete them on Spaces storage.

So this is not a simple button: this is a background process with heavy work and because this is doing sensible informations (hard deleting data on a production database/storage), it should be done really carefully.

**GDPR doesn't require a business to have a self-service delete account feature**, it just require a business to allow users to ask a deletion of their data, which you can ask already today by email/ to me and I'll delete everything myself manually :) 

Source:

"There’s no specifications around how these requests need to be made, which means users can make them either verbally or in writing. The only requirement is that if the request is valid, you must deal with it within a month." 

As we don't have a big user base for now, I think it's still realistic to do it manually.

Do you want me to hard delete your data?
